### ISSUE TITLE
list cpp symbols in the current buffer

### ISSUE THREAD

**Issue by kaarrot** [sonictk/lightweight-emacs#1]
Hi there. First of all this a great repo! I have been curating similar lightweight self contained instance for pretty much the same purposes :)
I have more of a question/advice to ask you - perhaps you can point me in the right direction.
In my day to day work with code navigation in cpp  I have been heavily relying on langue servers (such as cquery). What I haven't gotten to work reliably so far (without commit too much time to extend the server itself) is to list class members, free functions etc. in a current buffer. I know the regex is not the right tool for parsing cpp source tree - but this is what I have been using so far. It's janky and not not super reliable. My priority though is to stick with something which is self contained and does not rely on external libraries (for portability and fast setup). Do you know any lisp module which does this already?
Thank you!

**Comment by sonictk** [comment]
Sorry, I never noticed this question. If I understand your question correctly, You should be able to do this already with imenu (C-c h i if you're using my config), although I will also admit it doesn't manage to find everything sometimes. I wish `xref-find-references` was able to limit itself to the current buffer.

I recently switched my config to use clangd and eglot for handling C/C++ "intellisense", so hopefully that's been an improvement in that regard.

**Comment by kaarrot** [comment]
No worries and thanks that's good to know!
